#!/bin/bash
#----------------------------------------------------------------------------
# DATE        : March 2016
# AUTHOR      : Paolo Viotti
# DESCRIPTION : Bash script to run Conver tests
#----------------------------------------------------------------------------

usage() {
  echo "Usage: ./`basename $0` proper|run <nc> <store>"
  echo ""
  echo "    proper: run PropEr test on mock datastore"
  echo "    run <nc> <store>: run Conver"
  echo "        nc: number of clients"
  echo "        store: datastore under test (e.g., mock, riak, zk)"
}


if [ $# -eq 0 ]
then
  usage
  exit 1
fi

case $1 in
proper)
    erl -pa ./_build/default/lib/*/ebin -eval "conver_statem:test()." -s init stop -noshell
    ;;
run)
    if [ $# -ne 3 ]
    then
        usage
        exit 1
    else
        erl -pa ./_build/default/lib/*/ebin -noshell -eval "conver:main($2, $3)." -s init stop
    fi    
    ;;
*)
    usage
    exit 1
    ;;
esac



